services:
  fixture-predictions:
    build:
      context: .
      args:
        REACT_APP_ENTRA_CLIENT_ID: ${REACT_APP_ENTRA_CLIENT_ID}
        REACT_APP_ENTRA_TENANT_ID: ${REACT_APP_ENTRA_TENANT_ID}
        REACT_APP_ENTRA_REDIRECT_URI: ${REACT_APP_ENTRA_REDIRECT_URI}
        REACT_APP_PREDICTION_SAVE_ENDPOINT: ${REACT_APP_PREDICTION_SAVE_ENDPOINT}
    ports:
      - "8080:8080"
    env_file:
      - .env
