name: Docker Image CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker_publish:
    runs-on: "ubuntu-20.04"

    steps:
      - uses: actions/checkout@v2

      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ghcr.io/LeeKnight344/worldcuppredictions-fixture-predictions      # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
